export default function Premium() {
  return (
    <main style={{
      backgroundColor: "#0B0B0B",
      color: "white",
      minHeight: "100vh",
      padding: "20px",
      fontFamily: "Inter, sans-serif",
      textAlign: "center"
    }}>

      {/* HEADER */}
      <h1 style={{ fontSize: "28px", fontWeight: "bold" }}>
        Unlock Full Access
      </h1>

      {/* NAV */}
      <div style={{ marginBottom: "20px", marginTop: "10px" }}>
        <a href="/" style={{ marginRight: "15px", color: "#4ade80" }}>Home</a>
        <a href="/results" style={{ color: "#4ade80" }}>Results</a>
      </div>

      <p style={{ color: "#888", marginTop: "10px" }}>
        Access today’s qualified signals generated by the system.
      </p>

      {/* PRICING CARD */}
      <div style={{
        backgroundColor: "#1a1a1a",
        padding: "25px",
        borderRadius: "12px",
        marginTop: "30px"
      }}>
        <h2 style={{ fontSize: "24px" }}>$5 / Day</h2>

        <p style={{ color: "#888", marginTop: "10px" }}>
          Full access to all daily signals
        </p>

        <button style={{
          marginTop: "20px",
          padding: "14px",
          width: "100%",
          backgroundColor: "#4ade80",
          border: "none",
          borderRadius: "8px",
          fontWeight: "bold",
          fontSize: "16px"
        }}>
          Continue to Checkout
        </button>
      </div>

      {/* TRUST LINE */}
      <div style={{ marginTop: "30px" }}>
        <p style={{ color: "#888", fontSize: "14px" }}>
          Transparent results. No guarantees. Informational use only.
        </p>
        <p style={{ color: "#4ade80", fontSize: "14px", marginTop: "5px" }}>
          Price increases as system performance improves
        </p>
      </div>

    </main>
  );
}
